apiVersion: v1
kind: Service
metadata:
  name: ring-promoter
  labels:
    {{- include "rp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "rp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
